# Generated by Django 3.0.5 on 2020-04-10 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{3,}$')])),
                ('password', models.TextField(validators=[django.core.validators.RegexValidator('.{4,}')])),
                ('status_message', models.CharField(default='', max_length=30)),
                ('mastermind_wins', models.IntegerField(default=0)),
                ('blackjack_wins', models.IntegerField(default=0)),
                ('war_wins', models.IntegerField(default=0)),
                ('go_fish_wins', models.IntegerField(default=0)),
                ('connect_wins', models.IntegerField(default=0)),
            ],
        ),
    ]
