# Generated by Django 3.0.5 on 2020-04-23 01:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]{3,}$')])),
                ('password', models.TextField(validators=[django.core.validators.RegexValidator('.{4,}')])),
                ('status_message', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_played', models.CharField(choices=[('MASTERMIND', 'mastermind'), ('CONNECT4', 'connect4'), ('BLACKJACK', 'blackJack'), ('WAR', 'war'), ('GO_FISH', 'go_fish')], max_length=20)),
                ('did_win', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('meta', models.TextField(blank=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyarcade_backend.UserModel')),
            ],
        ),
    ]
