# Generated by Django 3.0.5 on 2020-05-04 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyarcade_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='game_played',
            field=models.CharField(choices=[('MASTERMIND', 'Mastermind'), ('CONNECT4', 'Connect 4'), ('BLACKJACK', 'Blackjack'), ('WAR', 'War'), ('GO_FISH', 'Go Fish'), ('HORSEMAN', 'Horseman')], max_length=20),
        ),
        migrations.CreateModel(
            name='FriendshipModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendship_status', models.CharField(choices=[('FRIENDS', 'friends'), ('PENDING', 'pending')], max_length=8)),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='pyarcade_backend.UserModel')),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='pyarcade_backend.UserModel')),
            ],
        ),
    ]
