image: "python:3.6"

stages:
  - build
  - test

build:
  stage: build
  script:
    - pip install -r frontend/requirements.txt
    - pip install -r backend/requirements.txt
    - pip install pytest

test_blackjack:
  stage: test
  script:
    - pytest frontend/tests/test_blackjack.py

test_connect4:
  stage: test
  script:
    - pytest frontend/tests/test_connect4.py

test_gofish:
  stage: test
  script:
    - pytest frontend/tests/test_gofish.py

test_horseman:
  stage: test
  script:
    - pytest frontend/tests/test_horseman.py

test_war:
  stage: test
  script:
    - pytest frontend/tests/test_war.py

test_input_system:
  stage: test
  script:
    - pytest frontend/tests/test_input_system.py

test_user_model:
  stage: test
  script:
    - cd backend
    - python manage.py test pyarcade_backend

test_db_model:
  stage: test
  script:
    - cd backend
    - python manage.py test pyarcade_backend
