version: "3"

services:
  proxy:
    build: ./proxy
    image: pyarcade_proxy
    container_name: "pyarcade_proxy"
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    restart: unless-stopped

  backend:
    build: ./backend
    image: pyarcade_backend
    container_name: "pyarcade_backend"
    volumes:
      - ./backend/db.sqlite3:/backend/db.sqlite3
    ports:
      - "127.0.0.1:8000:80"

  frontend:
    build: ./frontend
    image: pyarcade_frontend
    container_name: "pyarcade_frontend"
    tty: true
    stdin_open: true
